language: python
python:
- 3.4
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install -r requirements_tests.txt
script:
- python app/manage.py collectstatic --noinput
- coverage run --source app/ --omit */migrations/* --omit */management/* app/manage.py
  test
- ./runserver.sh
- python app/manage.py test tests.WebsocketsTests --settings=settings_selenium_tests
after_success:
- coveralls
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- sudo apt-get update -qq
- sudo apt-get install -qq firefox
sudo: true
services:
- redis-server
